# Generated by Django 5.0.1 on 2024-02-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_complaint_maintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='issue',
            field=models.CharField(max_length=200),
        ),
    ]
